export default [
  {
    id: '1',
    label: 'First Name',
    name: 'first_name',
    position: 0,
    checked: true,
    disabled: true,
  },
  { id: '2', label: 'Last Name', name: 'last_name', position: 1, checked: true, disabled: true },
  { id: '3', label: 'Email', name: 'email', position: 2, checked: true, disabled: false },
  {
    id: '4',
    label: 'Phone Number',
    name: 'phone_number',
    position: 3,
    checked: true,
    disabled: true,
  },
  { id: '5', label: 'Education', name: 'education', position: 4, checked: true, disabled: false },
  { id: '6', label: 'Industry', name: 'industry', position: 5, checked: true, disabled: false },
  {
    id: '7',
    label: 'Profession',
    name: 'profession',
    position: 6,
    checked: true,
    disabled: false,
  },
  {
    id: '8',
    label: 'Employment Status',
    name: 'employment_status',
    position: 7,
    checked: true,
    disabled: false,
  },
  { id: '9', label: 'Id Type', name: 'id_type', position: 8, checked: true, disabled: false },
  {
    id: '10',
    label: 'Id Number',
    name: 'id_number',
    position: 9,
    checked: true,
    disabled: false,
  },
  {
    id: '11',
    label: 'Levels',
    name: 'levels',
    position: 10,
    checked: true,
    disabled: true,
  },
  {
    id: '12',
    label: 'Gender',
    name: 'gender',
    position: 11,
    checked: true,
    disabled: false,
  },
  {
    id: '13',
    label: 'Policy Number',
    name: 'policy_number',
    position: 12,
    checked: true,
    disabled: false,
  },
  {
    id: '14',
    label: 'Date of Birth',
    name: 'dob',
    position: 13,
    checked: true,
    disabled: false,
  },
  {
    id: '15',
    label: 'Date of Joining',
    name: 'date_of_joining',
    position: 14,
    checked: true,
    disabled: false,
  },
  {
    id: '16',
    label: 'Self Employed?',
    name: 'self_employed',
    position: 15,
    checked: true,
    disabled: false,
  },
  {
    id: '17',
    label: 'Position?',
    name: 'position',
    position: 16,
    checked: true,
    disabled: false,
  },
  {
    id: '18',
    label: 'Groups?',
    name: 'groups',
    position: 17,
    checked: true,
    disabled: false,
  },
  {
    id: '19',
    label: 'Status?',
    name: 'status',
    position: 18,
    checked: true,
    disabled: false,
  },
  {
    id: '20',
    label: 'Passport Picture upload?',
    name: 'passport_picture',
    position: 19,
    checked: true,
    disabled: false,
  },
];
